#!/bin/sh

case "$1" in
	start)
		echo "Starting aesdsocket"
		start-stop-daemon --start --exec aesdsocket -- -d
		;;
	stop)
		echo "Stopping aesdsocket"
		start-stop-daemon --stop --exec aesdsocket
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0
